### ISSUE TITLE
'remove-gitlab-registration' script can invalidate in-use runner authentication token

### ISSUE THREAD

**Issue by schmidt-galen-heb** [cattle-ops/terraform-aws-gitlab-runner#1062]
# Describe the bug

We're in the process of upgrading to `7.2.2` + the [new runner registration workflow](https://docs.gitlab.com/ee/ci/runners/new_creation_workflow.html), and discovered an unfortunate race condition with `remove-gitlab-registration`.

Sometimes when cycling the agent instance, the AWS ASG will spin up the new instance before tearing down the old one. In that case, the following sequence of events can occur:

| Old Instance | New Instance |
| ------------- | ------------- |
| _starts_ | _n/a_ |
| [obtains `Runner Token 1` from Gitlab](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/8b73d42fe21602a343155743cb5d4beea0733b89/template/gitlab-runner.tftpl#L32-L81) | _n/a_ |
| [adds `Runner Token 1` to SSM](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/8b73d42fe21602a343155743cb5d4beea0733b89/template/gitlab-runner.tftpl#L82) | _n/a_ |
| _running_ | _n/a_ |
| _running_  | _starts_ |
| _running_ | [fetches and validates `Runner Token 1` from SSM](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/8b73d42fe21602a343155743cb5d4beea0733b89/template/gitlab-runner.tftpl#L21-L28) |
| _running_ | _finishes startup_ |
| _begins shutdown_ | _running_ |
| [remove_gitlab_registration.sh](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/8b73d42fe21602a343155743cb5d4beea0733b89/template/gitlab-runner.tftpl#L174-L180) runs and invalidates `Runner Token 1` | _running_ |
| _finishes shutdown_ | _receives 403 from Gitlab because `Runner Token 1` is now invalid_ |

# To Reproduce

The exact steps to reproduce seem to be tricky because the ASG seems inconsistent in how it's cycling the instances, but I believe it's:
1. Upgrade module to `7.2.2`
2. Use the [new runner registration workflow](https://docs.gitlab.com/ee/ci/runners/new_creation_workflow.html) in the [gitlab-runner.tftpl](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/8b73d42fe21602a343155743cb5d4beea0733b89/template/gitlab-runner.tftpl#L33-L62) script
    * To enable this, we're passing in:
    * `runner_gitlab.access_token_secure_parameter_store_name`
    * `runner_gitlab_registration_config.type`
    * `runner_gitlab_registration_config.project_id`
3. Run `terraform apply`
4. Wait for the ASG to stabilize
5. Make a change to the agent's user-data (e.g. by modifying `runner_install.pre_install_script`), and re-run `terraform apply`
6. Wait for the ASG to stabilize
7. Verify that the new agent instance cannot contact Gitlab because of `Forbidden` errors

# Expected behavior

The new agent instance can continue to run jobs from Gitlab.

# Additional context

As a concrete example, the new instance fetched and validated the token at `Jan 05 18:49:04 `, but the the original instance then started shutdown at `Jan 05 18:49:17` and invalidate the token, after which the new instance started logging the following:
```
Jan 05 18:50:51 gitlab-runner[2957]: {"level":"error","msg":"Checking for jobs... forbidden","runner":"<redacted>","status":"POST https://gitlab.com/api/v4/jobs/request: 403 Forbidden","time":"2024-01-05T18:50:51Z"}
Jan 05 18:50:54 gitlab-runner[2957]: {"level":"error","msg":"Checking for jobs... forbidden","runner":"<redacted>","status":"POST https://gitlab.com/api/v4/jobs/request: 403 Forbidden","time":"2024-01-05T18:50:54Z"}
Jan 05 18:50:57 gitlab-runner[2957]: {"level":"error","msg":"Checking for jobs... forbidden","runner":"<redacted>","status":"POST https://gitlab.com/api/v4/jobs/request: 403 Forbidden","time":"2024-01-05T18:50:57Z"}
Jan 05 18:50:57 gitlab-runner[2957]: {"level":"error","msg":"Runner \"<redacted>\" is unhealthy and will be disabled for 1h0m0s seconds!","time":"2024-01-05T18:50:57Z","unhealthy_requests":3,"unhealthy_requests_limit":3}
```

---

As a temporary workaround, we're passing the following into `runner_install.start_script`:
```sh
# This can be removed once https://github.com/cattle-ops/terraform-aws-gitlab-runner/issues/1062 is resolved.
echo 'Disabling "Remove the GitLab Runner from GitLab at shutdown" job...'
chmod a-x /opt/remove_gitlab_registration.sh || true
systemctl disable remove-gitlab-registration.service || true
systemctl stop remove-gitlab-registration.service || true
echo 'Done!'
```

**Comment by long-wan-ep** [comment]
We're also seeing this issue with the old registration token workflow. 2 more options I can think of for a fix:

- Don’t re-use runner auth tokens, instead generate a new one every time a new runner spins up. Instance refresh would take a bit longer since it’ll need to re-register the runner in GitLab every time, not sure if there are other side effects.
- Skip runner de-register during instance refresh. The `remove_gitlab_registration.sh` script would need logic to figure out if an instance refresh is the cause of instance termination and skip de-registering. Not sure how possible/reliable it would be since that script would need to know which ASG + instance refresh to look in, and if an ASG gets torn down while a refresh is in progress then de-registration may never happen.

**Comment by schmidt-galen-heb** [comment]
Tangential to the current issue, but in the previous version of the module we were using the [gitlab_runner](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/runner) resource (now [gitlab_user_runner](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/user_runner)) to manage the token, and then passing it in to the `cattle-ops/gitlab-runner/aws` module.

That way, the Gitlab Runner + token were entirely managed by Terraform, rather than the shell script.

Although it wouldn't solve the issue for users who want the module to manage their Gitlab Runners/tokens automatically, providing a way to pass in the registration token directly to the module rather than have it managed by the shell script would solve the issue for us.

**Comment by long-wan-ep** [comment]
Hi, can anyone think of any more solutions other than the ones proposed? Or is there a preference on the ones proposed? We're running into this issue almost every time we make an update to our runners and would love for it to be fixed, though I'm not sure which solution is the best since they all have some caveats.

**Comment by eyablonowitz** [comment]
In some testing, this race bites us > 50% of the time.  Seems better to take the suggestion of skipping the deregister and leaving cleanup to a manual task than the current situation which creates potential (likely) outages.

**Comment by kayman-mk** [comment]
Having downtimes is not acceptable here. I do not see any as I update the Runners in the early morning before the first developers are arriving.

Depending on how many Runner restarts you have, there can be many unused Runner registration in GitLab. What about the following proposal:

Instead of storing the Runner Token as plain string, we extend the secret with a in-use flag. Then we are able to skip the deregistration in case another Runner started slightly before the registration. So the secret would look like

```json
{
  "token": "null",
  "in_use": false
}
```

Old secrets are converted during Runner startup.

What do you think, @eyablonowitz, @long-wan-ep, @schmidt-galen-heb

**Comment by long-wan-ep** [comment]
If the `in-use` flag is set to true during runner start up, and then in the deregister script it checks the flag before deregistering, when would the flag be set to false to allow deregister to happen?

**Comment by kayman-mk** [comment]
Oh yes, a boolean does not work here. We need a number. The token is released if the number is zero.

In the example above, it is 1, then the next runner increments it to two and the first runner decrements it to one and does not release the token as it is still in use.

**Comment by long-wan-ep** [comment]
Ok gotcha, I think that's the best one out of the options proposed. As you mentioned, it's possible for it to fail since there's no atomic operation in SSM, but it should be pretty rare.

**Comment by kayman-mk** [comment]
@long-wan-ep Kindly ask for a quick review of #1102
