### ISSUE TITLE
Terraform destroy doesn't work 

### ISSUE THREAD

**Issue by kovacslaszlonik** [cattle-ops/terraform-aws-gitlab-runner#1073]
# Describe the bug

When we destroy the module, the requested spot instances are not canceled, and the terraform process timeouts on the following step:

We are using the currently latest stable, 7.2.2 version of this module.
The issue is due to the fact, that the `module.terminate_agent_hook` is deleted before the `aws_autoscaling_group.gitlab_runner_instance` module, so the lambda function is not triggered in time. 

It creates a loop that can be solved only with a manual interaction (terminate the spot instances) when we try to destroy the module.

# To Reproduce

1. Create your gitlab-runner from the 7.2.2 version 
2. Wait until it is initiated 
3. Run `terraform destroy`
4 You will see the timeout issue in this step since the spot runners are not terminated/canceled by the module itself:
```
module.spot_runner.aws_security_group.docker_machine[0]: Still destroying... [id=sg-04d8bdc6b45747c0c, 2m20s elapsed]
module.spot_runner.aws_security_group.docker_machine[0]: Still destroying... [id=sg-04d8bdc6b45747c0c, 2m30s elapsed]
```

# Expected behavior

We can destroy the module without any issues or manual interaction. 

# Additional context

Our runner setup:
- **runner_worker_docker_machine_fleet**  is enabled
- **runner_worker_docker_machine_instance_spot** is enabled
- **runner_worker** is docker+machine

**Comment by kayman-mk** [comment]
As far as I remember the problem was to detect the `destroy` operation and then run a script to stop the spot instances. There are also some other operations which might lead to manual interactions, e.g. changes to the security group which causes a recreate, ...

From my point of view the `terraform destroy` is not the main problem as you won't do that on regular bases. But updating the module and changing resources which are still in use is the main problem here. Not sure how to tackle it.

We have already a Lambda function in place killing the Runners in case the Agent goes down. At the moment this Lambda function is destroyed before the Agents shuts down. So maybe we can create a `depends_on` making sure that the Runners are destroyed as well. This would solve the `destroy` problem while updating the module might still causes errors.

What do you think?

**Comment by kovacslaszlonik** [comment]
Unfortunately, the `depends_on` solution can't work here, because the lambda function has several parameters from the created autoscaling groups. 
It would create a loop and break the terraform code (I've tested it on my forked code).

Basically, that's why I created this issue, because to solve the `destroy` situation, it will require either a brand new lambda function with different logic or the existing one needs to be refactored deeply.
