### ISSUE TITLE
spot_request_housekeeping resources are created when runner_worker_docker_machine_instance_spot enable is false

### ISSUE THREAD

**Issue by cmavromichalis** [cattle-ops/terraform-aws-gitlab-runner#1107]
# Describe the bug

When `runner_worker_docker_machine_instance_spot.enable` is set to `false` I see terraform still wants to create:
`module.terminate_agent_hook.aws_iam_role_policy_attachment.spot_request_housekeeping`
`module.terminate_agent_hook.aws_iam_policy.spot_request_housekeeping`

I feel like if spot instances are disabled it should not create these resources. 

# To Reproduce

1. Using the latest, set the variable `runner_worker_docker_machine_instance_spot.enable` to false
2. Run the terraform to create
3. See that it will create :
`module.terminate_agent_hook.aws_iam_role_policy_attachment.spot_request_housekeeping`
`module.terminate_agent_hook.aws_iam_policy.spot_request_housekeeping`

# Expected behavior

1. Set the variable `runner_worker_docker_machine_instance_spot.enable` to false
2. Run the terraform to create
3. See that it will not create resources related to spot requests.

# Additional context

Maybe I am missing something here, any help would be appreciated.

**Comment by kayman-mk** [comment]
The terminate agent lambda does the following:
1. cancel spot requests --> makes no sense here
2. terminates executors --> should be executed
3. removes unused SSH key pairs --> can you confirm, that you don't have any SSH keys?

1 makes no sense in your case, agree.
2 should be done to make sure that all executors are gone.
3 SSH keys are created by the fleet function. Could make sense in your case.

So this lambda was not written for spot instances exclusively. It also does the cleanup of other resources. That's why it was named `terminate_agent_hook`
