### ISSUE TITLE
IdleScaleFactor

### ISSUE THREAD

**Issue by liamcarter111** [cattle-ops/terraform-aws-gitlab-runner#556]
Is there any way to define `IdleScaleFactor`?
https://docs.gitlab.com/runner/configuration/autoscale.html#the-idlescalefactor-strategy

**Comment by npalm** [comment]
No not supported yet, but feel free to create a PR.

**Comment by tmeijn** [comment]
@kayman-mk, I was thinking to pick this up as a small contribution, but this would be a breaking change I think since we declare `runners_machine_autoscaling` as an `object`:

https://github.com/npalm/terraform-aws-gitlab-runner/blob/60f6748224d2b809e2e51fcc9fc172a73980e2ac/variables.tf#L275-L284

Adding that property here would mean that when users update the module they would have to specify `IdleScaleFactor` otherwise Terraform errors out.
