### ISSUE TITLE
Stuck on module.runner.module.cache[0].aws_s3_bucket.build_cache: Still creating...

### ISSUE THREAD

**Issue by zedtux** [cattle-ops/terraform-aws-gitlab-runner#847]
# Describe the bug

I have create a new AWS account, and an AIM user with the following permissions:
* IAMFullAccess
* PowerUserAccess

I have set the `registration_token` and `aws_region` variables in my `terraform.tfvars` file.

When I run `terraform apply` it creates a lot of things but finally got stuck forever on:

```
module.runner.module.cache[0].aws_s3_bucket.build_cache: Still creating... [14m20s elapsed]
module.runner.module.cache[0].aws_s3_bucket.build_cache: Still creating... [14m30s elapsed]
module.runner.module.cache[0].aws_s3_bucket.build_cache: Still creating... [14m40s elapsed]
```

# To Reproduce

See bellow

# Expected behavior

`terraform apply` should have succeeded.

# Additional context

I'm completely new to AWS.

**Comment by zedtux** [comment]
Oh, replacing all the permissions with AdministratorAccess "fixed" the issue.

What is the precise list of permissions I should have set to my IAM user please ?

**Comment by kayman-mk** [comment]
That is a good question. Usually you apply the changes in this module manually, so admin access is fine. In case you don't feel good, check this project to determine all policies needed: https://github.com/iann0036/iamlive

It's not a good idea to update this module via the GitLab Runner infrastructure. Usually the runners are shutdown due to the changes applied. Your pipeline fails as the runners are gone in between and you won't be able to restart them as not all changes have been applied.
