### ISSUE TITLE
What is the easiest way to cache docker images pull?

### ISSUE THREAD

**Issue by zedtux** [cattle-ops/terraform-aws-gitlab-runner#853]
First of all, thank you so much for this module, it really rocks and works out-of-the-box 🎉.

Using gitlab-runner on AWS is so powerful that we hit really quickly the Docker Hub pull rate limit which is really annoying.
I have set the `DOCKER_AUTH_CONFIG` which helped a little bit, but I reach again the limit very quickly.

So, what is the best way to handle that issue? ECR / EC2 running Docker registry as mirror / anything else?

I have read in other issues that adding a docker registry as mirror is not in the scope of this project, but in my eyes, as reaching this limit comes quickly, I think there should be some doc, or commented code, or whatever that could help us to onboard very quickly with a fast and stable runner. 🙏

**Comment by kayman-mk** [comment]
We use a [Nexus Repository OSS](https://www.sonatype.com/products/sonatype-nexus-oss-download) installation to proxy everything (Docker, Maven, ...).

If I remember correctly you can setup an ECR as pull through cache to proxy the DockerHub images. I found an article (didn't read completely): https://bobcares.com/blog/aws-ecr-pull-through-cache-docker-hub/

Makes sense to add a paragraph to the documentation.

**Comment by zedtux** [comment]
Would it be possible to use a module like [this one](https://registry.terraform.io/modules/TechToSpeech/ecr-mirror/aws/latest)?

**Comment by kayman-mk** [comment]
The tricky part is to get the profile to the executor machine running Terraform. But this should be possible with `var.runners_userdata`. Looks like a useable solution.

**Comment by zedtux** [comment]
Sorry, unfortunately I'm too new to the AWS things and this Terraform module to understand that. 😞

**Comment by zedtux** [comment]
Hey @kayman-mk, this issue is completed? Great news! How can I enable/configure it please?

**Comment by kayman-mk** [comment]
Closed, because it is out of scope. The Docker infrastructure is nothing we will ever touch. There are a few options available: You named one and you find others in #853.

**Comment by kayman-mk** [comment]
The Nexus is a good option because you can cache nearly every registry and not only Docker. As far as I know there is a [free version available](https://www.sonatype.com/products/sonatype-nexus-oss-download). All you need is a EC2 instance and a S3 bucket to store the cached data.

```
module "gitlab_runner" {
  # ...
  docker_machine_options              = ["engine-registry-mirror=https://my.docker.nexus.endpoint"]
  # ...
}
```

Authentication works via a CI/CD variable set in GitLab
```
{"auths":{"https://my.docker.nexus.endpoint":{"auth":"<base64 encoded username:password>"}}}
```

Using ECR as cache means that you have to authenticate against the ECR and I have no idea how it works. I know that there is the ECR credential helper which can be used. Maybe you find some useful information in #320 on how to configure it. It seems pretty straight forward. #189 might also help.

[This comment](https://github.com/cattle-ops/terraform-aws-gitlab-runner/issues/270#issuecomment-952391710) suggests to use a mirror at GCP. Seems to be the easiest solution.

**Comment by zedtux** [comment]
Thank you for your comment!

I went through the #320 and tried `runners_install_amazon_ecr_credential_helper` but this for the small EC2 instance, running gitlab runner "master", not for the EC2 instances running gitlab runner "workers".

Regarding #189, that's an interesting one that I will give a try, thank you!
